FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
COPY packages/frontend/package*.json ./packages/frontend/
RUN npm install --workspace=packages/frontend --ignore-scripts
COPY packages/frontend ./packages/frontend
COPY package*.json ./
ARG VITE_API_URL=http://2.25.185.223/api
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build -w packages/frontend

FROM nginx:alpine AS runner
COPY --from=builder /app/packages/frontend/dist /usr/share/nginx/html
COPY nginx.frontend.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
