-- CreateTable TBLCHATBOTLIGHTFLUXO
CREATE TABLE "TBLCHATBOTLIGHTFLUXO" (
    "id" TEXT NOT NULL,
    "doctorId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "keywords" TEXT NOT NULL,
    "welcomeMessage" TEXT NOT NULL,
    "options" JSONB NOT NULL DEFAULT '[]',
    "maxAttempts" INTEGER NOT NULL DEFAULT 3,
    "fallbackMessage" TEXT NOT NULL DEFAULT 'Não consegui entender. Vou transferir para um atendente.',
    "active" BOOLEAN NOT NULL DEFAULT true,
    "executions" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "TBLCHATBOTLIGHTFLUXO_pkey" PRIMARY KEY ("id")
);

-- CreateTable TBLCHATBOTLIGHTQUICKREPLY
CREATE TABLE "TBLCHATBOTLIGHTQUICKREPLY" (
    "id" TEXT NOT NULL,
    "doctorId" TEXT NOT NULL,
    "keyword" TEXT NOT NULL,
    "response" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "TBLCHATBOTLIGHTQUICKREPLY_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLCHATBOTLIGHTFLUXO_doctorId_idx" ON "TBLCHATBOTLIGHTFLUXO"("doctorId");
CREATE INDEX "TBLCHATBOTLIGHTQUICKREPLY_doctorId_idx" ON "TBLCHATBOTLIGHTQUICKREPLY"("doctorId");

-- AddForeignKey
ALTER TABLE "TBLCHATBOTLIGHTFLUXO" ADD CONSTRAINT "TBLCHATBOTLIGHTFLUXO_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "TBLUSUARIO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TBLCHATBOTLIGHTQUICKREPLY" ADD CONSTRAINT "TBLCHATBOTLIGHTQUICKREPLY_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "TBLUSUARIO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
