-- CreateTable TBLCHATBOTLIGHTTEMPLATE
CREATE TABLE "TBLCHATBOTLIGHTTEMPLATE" (
    "id" TEXT NOT NULL,
    "doctorId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "variables" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "TBLCHATBOTLIGHTTEMPLATE_pkey" PRIMARY KEY ("id")
);

-- CreateTable TBLCHATBOTLIGHTCONFIG
CREATE TABLE "TBLCHATBOTLIGHTCONFIG" (
    "id" TEXT NOT NULL,
    "doctorId" TEXT NOT NULL,
    "module" TEXT NOT NULL,
    "triggerEvent" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "templateId" TEXT,
    "delayMinutes" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "TBLCHATBOTLIGHTCONFIG_pkey" PRIMARY KEY ("id")
);

-- CreateTable TBLCHATBOTLIGHTLOG
CREATE TABLE "TBLCHATBOTLIGHTLOG" (
    "id" TEXT NOT NULL,
    "doctorId" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "recipientName" TEXT,
    "content" TEXT NOT NULL,
    "module" TEXT NOT NULL,
    "triggerEvent" TEXT,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "errorMessage" TEXT,
    "sentAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "TBLCHATBOTLIGHTLOG_pkey" PRIMARY KEY ("id")
);

-- CreateTable TBLCHATBOTLIGHTSETTINGS
CREATE TABLE "TBLCHATBOTLIGHTSETTINGS" (
    "id" TEXT NOT NULL,
    "doctorId" TEXT NOT NULL,
    "enabledScreens" TEXT[] DEFAULT ARRAY['agenda', 'pacientes', 'prontuario', 'avaliacao', 'financeiro']::TEXT[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "TBLCHATBOTLIGHTSETTINGS_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TBLCHATBOTLIGHTTEMPLATE_doctorId_idx" ON "TBLCHATBOTLIGHTTEMPLATE"("doctorId");
CREATE INDEX "TBLCHATBOTLIGHTLOG_doctorId_idx" ON "TBLCHATBOTLIGHTLOG"("doctorId");
CREATE INDEX "TBLCHATBOTLIGHTLOG_doctorId_createdAt_idx" ON "TBLCHATBOTLIGHTLOG"("doctorId", "createdAt");

-- CreateUniqueIndex
CREATE UNIQUE INDEX "TBLCHATBOTLIGHTCONFIG_doctorId_module_triggerEvent_key" ON "TBLCHATBOTLIGHTCONFIG"("doctorId", "module", "triggerEvent");
CREATE UNIQUE INDEX "TBLCHATBOTLIGHTSETTINGS_doctorId_key" ON "TBLCHATBOTLIGHTSETTINGS"("doctorId");

-- AddForeignKey
ALTER TABLE "TBLCHATBOTLIGHTTEMPLATE" ADD CONSTRAINT "TBLCHATBOTLIGHTTEMPLATE_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "TBLUSUARIO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TBLCHATBOTLIGHTCONFIG" ADD CONSTRAINT "TBLCHATBOTLIGHTCONFIG_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "TBLUSUARIO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TBLCHATBOTLIGHTCONFIG" ADD CONSTRAINT "TBLCHATBOTLIGHTCONFIG_templateId_fkey" FOREIGN KEY ("templateId") REFERENCES "TBLCHATBOTLIGHTTEMPLATE"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TBLCHATBOTLIGHTLOG" ADD CONSTRAINT "TBLCHATBOTLIGHTLOG_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "TBLUSUARIO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TBLCHATBOTLIGHTSETTINGS" ADD CONSTRAINT "TBLCHATBOTLIGHTSETTINGS_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "TBLUSUARIO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
